### ISSUE TITLE
Dataset and evaluation

### ISSUE THREAD

**Issue by Yc-scu** [cwmok/LapIRN#16]
Hi. Great work is done! Thank you for sharing this code.
This code is very clear and easy to understand. This is my first successful run code in the field of medical image registration. I have two questions to ask you.
First, I only found the preprocessed OASIS dataset. I also want to get the results in LPBA40 dataset. Can you release the preprocessed LPBA40 dataset.
Second, when running the test code, the quantitative scores such as Dice are not displayed. Can you release this part of the code?
Looking forward to your reply.

**Comment by cwmok** [comment]
Hi @Yc-scu,

>> Can you release the preprocessed LPBA40 dataset?

We don't have the right/license to re-distribute the dataset. But you can easily download it here: https://www.loni.usc.edu/research/atlas_downloads, select "LPBA40 Subjects Delineation Space: MRI and label files in delineation space" should be sufficient.

>> Second, when running the test code, the quantitative scores such as Dice are not displayed. Can you release this part of the code?

Currently, we didn't have any plan for releasing the evaluation code since it is highly customized with our preprocessed data. Yet, for the Dice score computation, we use the function in [here ](https://github.com/cwmok/LapIRN/blob/583b32d0b469108de2b1a7369b6f66803c45d74b/Code/Train_LapIRN_diff_resize.py#L69-L82).

Thanks for your interest in our work. :D

**Comment by Yc-scu** [comment]
Thank you for your reply, which is very useful to me.
Thanks a lot!

**Comment by tuffr5** [comment]
The above one seemed to be expired. Use this link to download: https://resource.loni.usc.edu/resources/atlases-downloads/.
