### ISSUE TITLE
Something question about smooth_loss

### ISSUE THREAD

**Issue by NOTGOOOOD** [cwmok/LapIRN#22]
Hello!
I am confused as to why the velocity field is performed as follows before feeding in smoothing loss.
`  _, _, z, y, x = F_xy.shape`
 ` F_xy[:, 0, :, :, :] = F_xy[:, 0, :, :, :] * (x - 1)`
` F_xy[:, 1, :, :, :] = F_xy[:, 1, :, :, :] * (y - 1)`
` F_xy[:, 2, :, :, :] = F_xy[:, 2, :, :, :] * (z - 1)`
` loss_regulation = loss_smooth(F_xy)`

**Comment by cwmok** [comment]
Hi @NOTGOOOOD,

This step is to transform the normalized velocity field (within the range [-1, 1]) into an unnormalized one. This step is optional. However, if you remove this step, you will need to search for a new hyperparameter \lambda (--smooth) in order to enforce suitable smoothness regularization to the velocity field.

**Comment by NOTGOOOOD** [comment]
> `self.output_lvl1` uses a softsign activation function to output a normalized velocity field/displacement vector field. The output of `self.output_lvl1` is already normalized. `self.range_flow` further restricts the normalized field from [-1, 1] to [-self.range_flow, self.range_flow].

I got it! I really appreciate your help!
