### ISSUE TITLE
Pre-processing of NLST 

### ISSUE THREAD

**Issue by varsha-raveendran** [cwmok/LapIRN#24]
Hello @cwmok, 

I'm setting up LapIRN as a baseline with NLST data. The data is from the L2R challenge 2022. 

1. These are the steps that I follow: Does this look ok?
  1. Clip the intensities between -1200 and 600. 
  2. Normalize using min-max
  
Example of a preprocessed scan is shown here:

![image](https://github.com/cwmok/LapIRN/assets/67820303/23f20570-4b1a-4cc2-ae81-c55384c45ce5)

2. I would like your comments on the following: my project requires comparing methods using masked inputs vs. not using masked inputs. In other issues, you have mentioned that the background intensities need to be zero. So, if I use non-masked inputs preprocessed with the steps given above, does it mean that the results will be poor? Would it make a difference if I add a supervised loss? I'd appreciate your thoughts.

**Comment by cwmok** [comment]
Hi @varsha-raveendran,

1. Your preprocessing pipeline looks good to me. 
2. I would like to clarify the "cost function masking" technique. Usually, we will mask the similarity function using the mask from the fixed image, e.g., see for https://simpleelastix.readthedocs.io/Introduction.html#masks more details, instead of directly masking the input images. Moreover, learning the registration without a mask will not make the results poor. We need masks for this task mainly because all the landmarks are annotated within the lung lobe. If the rigid structures are your region of interest, then registration without any mask will yield a more desirable result.

Hope these suggestions help.

Regards,
Tony

**Comment by varsha-raveendran** [comment]
Thanks @cwmok. The explanations and link does help :) 

I have a couple of questions regarding the deformation field and its format. It would help if you could provide any information. I'm using 'Train_LapIRN_diff_nlst' to train the baseline. I understand that F_X_Y is normalized and in  [X, Y, Z, [z, y, x]]. 

1. Since scipy's map_coordinates function needs the field to be in [X, Y, Z, [x, y, z]] format, do I need to unnormalize and **flip** the z and x axes to use map_coordinates to warp the fixed keypoints?

2. Also, I've been trying to understand if the keypoints provided by L2R is in [x,y,z] format as this makes a difference when I calculate TRE. Could you please help here?

3. In generate_grid_unit function, I don't understand the purpose of swapping axes 1 and 2. 
![image](https://github.com/cwmok/LapIRN/assets/67820303/11009529-53df-4a02-8b3f-832045ef9834)

Let me know if you'd prefer if I open this as a different issue/discussion.

**Comment by cwmok** [comment]
Hi @varsha-raveendran,

1. Yes, you need to unnormalize and flip the z and x axes to use map_coordinates to warp the fixed keypoints. See my response in https://github.com/cwmok/Conditional_LapIRN/issues/11.
2. Yes, they are in [x, y, z] format and in voxel space. In order to calculate TRE, see my response in https://github.com/cwmok/Conditional_LapIRN/issues/11.
3. I borrow the code from IC-Net. The core idea is to generate an identity grid that matches the input of the grid_sample function in Pytorch.
4. Yes, upsampling the normalized flow field first, and then doing the flipping.
5. I saw that you are using the diffeomorphic version of LapIRN as the baseline. During the L2R challenge, I found that the diff version of LapIRN is rather unstable in this task. You may want to switch to the displacement vector field version if you found that the training is collapsed using diff_LapIRN.

**Comment by varsha-raveendran** [comment]
Thanks again :)
