### ISSUE TITLE
Registration image shifting

### ISSUE THREAD

**Issue by MoXiaoYing96** [cwmok/LapIRN#6]
Hi Tony, I am using LapIRN code _"Train_LapIRN_diff.py"_ to train registration model by using OASIS-3 dataset and I met some trouble about that.
I used OASIS images which size is (176, 256, 256) and change the code of image size.This is my origin image:
(Since T2 image is difficult to peel the skull, I used origin images)
![微信图片_20210922154629](https://user-images.githubusercontent.com/52778658/134303977-806b4075-da69-47c9-b183-8049363b4e4a.png)
![微信图片_20210922154853](https://user-images.githubusercontent.com/52778658/134304011-8f550ebf-9052-4520-be54-27473188174f.png)

After three levels training of 40000, 40000, 80000, the registration image is as below:
![微信图片_20210922155417](https://user-images.githubusercontent.com/52778658/134304442-e1d6fbfa-4c78-426e-8a3f-94964235d084.png)

And I tried to not change the image size, I resize image into (160, 192, 144) as same as your orgin code, but the image still shifting and crooked from the center:
![微信图片_20210922155923](https://user-images.githubusercontent.com/52778658/134305226-06ae2b67-e2c2-4131-9ed8-8ceff2bf2dca.png)

I wonder why this problem came out and should I change some parameters of training to solve this problem?

Your warm help will be appreciated! :)

**Comment by cwmok** [comment]
Hi @MoXiaoYing96,
I think you are trying to register T1 weighted scan to a T2 scan, which is a multi-modal registration problem. By default, our code uses NCC as the similarity function and it is not capable of multi-modal registration (because the structures from two scans don't hold a linear relation in intensity. You need to consider using a multi-modal registration method/changing the similarity function. For example, DEEDS/MI/MIND-SSC/NGF/Garbor filters are great methods for multi-model registration. 

And finally, brain registration without skull stripped is difficult. Yet, applying the brain mask may help (You may read this article for more details about masking https://simpleelastix.readthedocs.io/Introduction.html)

**Comment by MoXiaoYing96** [comment]
Hi, Tony.
Thanks for your advise! I am planing to combine MIND with LapIRN to solve the multi-model registration problem in the future.
I tried to strip the T2 brain skull by using FreeSurfer, but it works not well, thanks for your skull stripping method advise again!
Wish u have a good day!
